readme.md changes for locked images
rapidfort/community-images pull request #452
Opened 2024-02-19 14:46 UTC by kanavphull

### Description of the change

Created a new jinja template for locked images and added a function in `image_generator.sh` script to generate readmes for locked images

2024-02-20 17:09 UTC, AnmolVirdi requested changes

2024-02-20 17:09 UTC, AnmolVirdi commented on scripts/image_generator.sh
>    gen_image_readme
Can we add both in the same bash function?

gen_image_readme()
For image in image.lst
[ If image exists in image-locked.lst: we use locked jinja template]
[else: use usual one]

2024-02-21 23:19 UTC, mehran-rf requested changes

2024-02-29 17:30 UTC, AnmolVirdi approved these changes

2024-02-29 17:48 UTC, AnmolVirdi approved these changes

2024-02-29 17:50 UTC, merged