Addition of kafka-ib
rapidfort/community-images pull request #522
Opened 2024-04-14 20:11 UTC by kanavphull

2024-04-15 09:28 UTC, AnmolVirdi requested changes
- Assets directory missing
- .rfignore missing

2024-04-15 09:28 UTC, AnmolVirdi commented on community_images/kafka/ironbank/image.yml
> +needs_common_commands: False
Why are we not adding common commands here?

2024-04-16 19:04 UTC, Kirandeep-Singh-Khehra commented on community_images/kafka/ironbank/image.yml
> +source_image_repo_link: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fbitnami%2Fkafka
Please remove `opensource`. Bitnami does not come under opensource project/directory on repo1 or registry1.

2024-04-17 20:19 UTC, AnmolVirdi approved these changes

2024-04-22 15:16 UTC, merged