Addition of postgres-exporter-ib
rapidfort/community-images pull request #632
Opened 2024-05-31 21:07 UTC by kanavphull

2024-06-01 01:00 UTC, AnmolVirdi requested changes

2024-06-01 01:00 UTC, AnmolVirdi commented on community_images/postgres-exporter/ironbank/dc_coverage.sh
Does this cover all possible functionality for Postgres exporter?

2024-06-01 09:52 UTC, kanavphull commented on community_images/postgres-exporter/ironbank/docker-compose.yml
> +      - "5432:5432"
Sure, will add that. We would have to fetch the dynamically assigned port in dc_coverage.sh

2024-06-01 11:14 UTC, kanavphull commented on community_images/postgres-exporter/ironbank/docker-compose.yml
> +    image: postgres:latest
tested and added ✅

2024-06-01 11:20 UTC, kanavphull commented on community_images/postgres-exporter/ironbank/dc_coverage.sh
yes. I have added some more flags in docker-compose.yml itself to exercise some more functionality.

2024-06-03 09:51 UTC, AnmolVirdi commented on community_images/postgres-exporter/ironbank/docker-compose.yml
> +  postgres-data:
Please set up local driver here. `driver: local`

2024-06-03 10:37 UTC, kanavphull commented on community_images/postgres-exporter/ironbank/docker-compose.yml
> +  postgres-data:
sure

2024-06-03 16:30 UTC, merged